AWSTemplateFormatVersion: "2010-09-09"
Description: "Billing alarm"


Parameters:

  AdminEmail:
    Type: String

  AlarmThreshold:
    Type: Number


Resources:

  SpendingNotification:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: !Ref AdminEmail
          Protocol: "Email"

  SpendingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 
        'Fn::Join':
          - ''
          - - Alarm if AWS spending is over $
            - Ref: AlarmThreshold
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Dimensions:
      - Name: Currency
        Value: USD
      Statistic: Maximum
      Period: '21600'
      EvaluationPeriods: '1'
      Threshold: !Ref AlarmThreshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: 
        - !Ref SpendingNotification
      InsufficientDataActions: 
        - !Ref SpendingNotification